services:
    db:
        image: mysql:8
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    web:
        build: .
        restart: always
        depends_on:
            - db
        env_file:
            - .env
        environment:
            DATABASE_HOST: ${DATABASE_HOST}
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - ./wait-for-it.sh:/wait-for-it.sh
        command:
            [
                "./wait-for-it.sh",
                "db:3306",
                "--",
                "python",
                "manage.py",
                "runserver",
                "0.0.0.0:8000",
            ]

volumes:
    mysql_data:
