# Generated by Django 5.1.4 on 2025-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
