# Generated by Django 5.1.4 on 2025-01-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_presentation_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.feedbackcomment'),
        ),
    ]
